version: '3'

services:
  server:
    build: .
    container_name: gopdf-server
    ports:
      - "8090:8090"
    volumes:
      - .:/usr/src/app
    environment:
      GOTENBERG_URL: http://gotenberg:3000

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"
